// rumbo-alfa-centauri/data.js
'use strict';

const QUESTIONS = [
  // --- Nivel 9-11 · Espacio y astronomía ---
  { id: 'espacio-9-11-01', level: '9-11', category: 'espacio', question: '¿Cuál es el planeta más cercano al Sol?', options: ['Venus', 'Mercurio', 'Marte'], correctIndex: 1, explanation: 'Mercurio es el planeta más cercano al Sol; tarda solo 88 días en darle la vuelta.' },
  { id: 'espacio-9-11-02', level: '9-11', category: 'espacio', question: '¿Qué astro ilumina la Tierra durante el día?', options: ['La Luna', 'El Sol', 'Una estrella lejana'], correctIndex: 1, explanation: 'El Sol es una estrella que emite su propia luz; la Luna solo refleja la luz del Sol.' },
  { id: 'espacio-9-11-03', level: '9-11', category: 'espacio', question: '¿Cómo se llama el planeta rojo?', options: ['Júpiter', 'Marte', 'Saturno'], correctIndex: 1, explanation: 'Marte se ve rojizo por el óxido de hierro en su superficie, el mismo compuesto que le da color al óxido de un metal.' },
  { id: 'espacio-9-11-04', level: '9-11', category: 'espacio', question: '¿Qué es un cometa?', options: ['Una estrella fugaz', 'Una bola de hielo y polvo que viaja por el espacio', 'Un satélite artificial'], correctIndex: 1, explanation: 'Los cometas son bolas de hielo, polvo y roca que dejan una cola brillante al acercarse al Sol.' },
  { id: 'espacio-9-11-05', level: '9-11', category: 'espacio', question: '¿Cuántos planetas hay en el sistema solar?', options: ['7', '8', '9'], correctIndex: 1, explanation: 'Son 8 desde que Plutón fue reclasificado como planeta enano en 2006.' },
  { id: 'espacio-9-11-06', level: '9-11', category: 'espacio', question: '¿Qué necesita un astronauta para respirar en el espacio?', options: ['Nada, hay aire', 'Un traje con oxígeno', 'Solo un casco'], correctIndex: 1, explanation: 'En el espacio no hay aire, así que los astronautas llevan oxígeno en su traje.' },
  { id: 'espacio-9-11-07', level: '9-11', category: 'espacio', question: '¿Qué es la Vía Láctea?', options: ['Un planeta', 'La galaxia donde vivimos', 'Una nave espacial'], correctIndex: 1, explanation: 'La Vía Láctea es la galaxia que contiene el Sol, la Tierra y miles de millones de estrellas más.' },
  { id: 'espacio-9-11-08', level: '9-11', category: 'espacio', question: '¿Por qué vemos diferentes fases de la Luna?', options: ['La Luna cambia de tamaño', 'Vemos distintas partes iluminadas por el Sol', 'Se apaga y se enciende'], correctIndex: 1, explanation: 'La Luna no emite luz propia; vemos distintas porciones iluminadas según su posición respecto al Sol y la Tierra.' },
  { id: 'espacio-9-11-09', level: '9-11', category: 'espacio', question: '¿Cuál es el planeta con más anillos visibles?', options: ['Saturno', 'Marte', 'Mercurio'], correctIndex: 0, explanation: 'Saturno tiene el sistema de anillos más grande y visible, hechos de hielo y roca.' },
  { id: 'espacio-9-11-10', level: '9-11', category: 'espacio', question: '¿Cuánto tarda la luz del Sol en llegar a la Tierra?', options: ['Unos 8 minutos', '1 segundo', '1 año'], correctIndex: 0, explanation: 'La luz viaja rapidísimo, pero el Sol está tan lejos que tarda unos 8 minutos en llegar a nosotros.' },

  // --- Nivel 9-11 · Física y naturaleza ---
  { id: 'fisica-9-11-01', level: '9-11', category: 'fisica', question: '¿Qué cae más rápido en la Luna: una pluma o un martillo?', options: ['La pluma', 'El martillo', 'Caen igual de rápido'], correctIndex: 2, explanation: 'En la Luna no hay aire que frene a la pluma, así que ambos caen a la misma velocidad por la gravedad lunar.' },
  { id: 'fisica-9-11-02', level: '9-11', category: 'fisica', question: '¿Por qué vemos un arcoíris después de la lluvia?', options: ['La luz del Sol se refleja y separa en colores al pasar por gotas de agua', 'El agua se pinta de colores', 'Es un reflejo de las nubes'], correctIndex: 0, explanation: 'Las gotas de agua actúan como pequeños prismas que separan la luz blanca del Sol en los colores que la forman.' },
  { id: 'fisica-9-11-03', level: '9-11', category: 'fisica', question: '¿Qué hace que un imán atraiga un clip de metal?', options: ['El calor', 'Un campo magnético invisible', 'La electricidad estática'], correctIndex: 1, explanation: 'Los imanes generan un campo magnético invisible que atrae materiales como el hierro y el acero.' },
  { id: 'fisica-9-11-04', level: '9-11', category: 'fisica', question: '¿Por qué flota un barco de metal en el agua si el metal es pesado?', options: ['Porque el agua es mágica', 'Porque su forma hueca desplaza suficiente agua para flotar', 'Porque va muy despacio'], correctIndex: 1, explanation: 'La forma hueca del barco hace que desplace un gran volumen de agua, generando suficiente empuje para flotar aunque el metal sea denso.' },
  { id: 'fisica-9-11-05', level: '9-11', category: 'fisica', question: '¿Qué es el sonido?', options: ['Luz que vibra', 'Vibraciones que viajan por el aire (u otro medio)', 'Un tipo de viento'], correctIndex: 1, explanation: 'El sonido son ondas de vibración que se propagan por el aire, el agua u otros materiales hasta llegar a nuestros oídos.' },
  { id: 'fisica-9-11-06', level: '9-11', category: 'fisica', question: '¿Por qué en el espacio no se escuchan sonidos?', options: ['Los astronautas están sordos por el casco', 'No hay aire (ni otro medio) para que el sonido viaje', 'Los sonidos son muy débiles'], correctIndex: 1, explanation: 'El sonido necesita un medio (como el aire) para propagarse; en el vacío del espacio no hay partículas que lo transmitan.' },
  { id: 'fisica-9-11-07', level: '9-11', category: 'fisica', question: '¿Qué fuerza te hace regresar al suelo cuando saltas?', options: ['El viento', 'La gravedad', 'La presión del aire'], correctIndex: 1, explanation: 'La gravedad de la Tierra atrae todo hacia su centro, por eso siempre regresamos al suelo después de saltar.' },
  { id: 'fisica-9-11-08', level: '9-11', category: 'fisica', question: '¿Por qué el hielo flota en el agua?', options: ['Porque es más frío', 'Porque es menos denso que el agua líquida', 'Porque el agua lo empuja hacia arriba con viento'], correctIndex: 1, explanation: 'Al congelarse, el agua forma una estructura con más espacio entre sus moléculas, haciéndola menos densa que el agua líquida.' },
  { id: 'fisica-9-11-09', level: '9-11', category: 'fisica', question: '¿Qué es un relámpago?', options: ['Una descarga eléctrica gigante entre nubes o hacia el suelo', 'Una explosión de aire caliente', 'Una estrella fugaz cercana'], correctIndex: 0, explanation: 'Es una enorme chispa de electricidad que se libera cuando se acumula suficiente carga eléctrica entre las nubes.' },
  { id: 'fisica-9-11-10', level: '9-11', category: 'fisica', question: '¿Por qué vemos el rayo antes de escuchar el trueno?', options: ['Porque el sonido viaja mucho más despacio que la luz', 'Porque el trueno ocurre después', 'Porque el rayo hace ruido primero'], correctIndex: 0, explanation: 'La luz viaja muchísimo más rápido que el sonido, así que vemos el destello casi al instante y el sonido del trueno llega segundos después.' },

  // --- Nivel 9-11 · Cuerpo humano y biología ---
  { id: 'biologia-9-11-01', level: '9-11', category: 'biologia', question: '¿Cuál es el órgano que bombea la sangre por todo el cuerpo?', options: ['El cerebro', 'El corazón', 'El estómago'], correctIndex: 1, explanation: 'El corazón es un músculo que late para impulsar la sangre a través de todo el cuerpo.' },
  { id: 'biologia-9-11-02', level: '9-11', category: 'biologia', question: '¿Cuántos huesos tiene aproximadamente el cuerpo de un adulto?', options: ['106', '206', '306'], correctIndex: 1, explanation: 'Un adulto tiene alrededor de 206 huesos (los bebés nacen con más, pero muchos se fusionan al crecer).' },
  { id: 'biologia-9-11-03', level: '9-11', category: 'biologia', question: '¿Qué órgano usamos principalmente para respirar?', options: ['Los pulmones', 'El hígado', 'Los riñones'], correctIndex: 0, explanation: 'Los pulmones absorben el oxígeno del aire y liberan dióxido de carbono cuando respiramos.' },
  { id: 'biologia-9-11-04', level: '9-11', category: 'biologia', question: '¿Para qué sirven los glóbulos rojos?', options: ['Combatir infecciones', 'Transportar oxígeno por el cuerpo', 'Digerir alimentos'], correctIndex: 1, explanation: 'Los glóbulos rojos contienen hemoglobina, que se une al oxígeno y lo lleva a todas las células del cuerpo.' },
  { id: 'biologia-9-11-05', level: '9-11', category: 'biologia', question: '¿Qué parte del cuerpo controla todos tus pensamientos y movimientos?', options: ['El corazón', 'El cerebro', 'El estómago'], correctIndex: 1, explanation: 'El cerebro es el centro de control del cuerpo: procesa la información y envía órdenes a través de los nervios.' },
  { id: 'biologia-9-11-06', level: '9-11', category: 'biologia', question: '¿Por qué necesitamos dormir?', options: ['Solo para pasar el tiempo', 'Para que el cuerpo y el cerebro descansen y se recuperen', 'Porque los ojos se cansan de ver'], correctIndex: 1, explanation: 'Durante el sueño, el cuerpo repara tejidos y el cerebro organiza la información aprendida durante el día.' },
  { id: 'biologia-9-11-07', level: '9-11', category: 'biologia', question: '¿Qué son los músculos?', options: ['Tejidos que se contraen para producir movimiento', 'Huesos flexibles', 'Parte del sistema digestivo'], correctIndex: 0, explanation: 'Los músculos se contraen y relajan para mover el cuerpo, desde caminar hasta parpadear.' },
  { id: 'biologia-9-11-08', level: '9-11', category: 'biologia', question: '¿Cuál es el órgano más grande del cuerpo humano?', options: ['El hígado', 'La piel', 'El cerebro'], correctIndex: 1, explanation: 'La piel cubre todo el cuerpo y protege contra gérmenes, regula la temperatura y nos da el sentido del tacto.' },
  { id: 'biologia-9-11-09', level: '9-11', category: 'biologia', question: '¿Qué le pasa a la comida en el estómago?', options: ['Se guarda sin cambios', 'Se mezcla con jugos gástricos que empiezan a descomponerla', 'Se convierte directo en energía'], correctIndex: 1, explanation: 'El estómago produce ácidos y jugos que descomponen la comida para que el cuerpo pueda absorber sus nutrientes.' },
  { id: 'biologia-9-11-10', level: '9-11', category: 'biologia', question: '¿Cuántos sentidos básicos solemos reconocer?', options: ['3', '5', '8'], correctIndex: 1, explanation: 'Los cinco sentidos clásicos son la vista, el oído, el olfato, el gusto y el tacto.' },

  // --- Nivel 9-11 · Química y materia ---
  { id: 'quimica-9-11-01', level: '9-11', category: 'quimica', question: '¿Cuáles son los tres estados básicos de la materia?', options: ['Sólido, líquido y gaseoso', 'Caliente, frío y templado', 'Duro, blando y suave'], correctIndex: 0, explanation: 'La materia puede existir en distintos estados según su temperatura y presión; los tres más comunes son sólido, líquido y gas.' },
  { id: 'quimica-9-11-02', level: '9-11', category: 'quimica', question: '¿Qué le pasa al agua cuando se calienta a 100°C al nivel del mar?', options: ['Se congela', 'Hierve y se convierte en vapor', 'Cambia de color'], correctIndex: 1, explanation: 'A 100°C, al nivel del mar, el agua alcanza su punto de ebullición y pasa de líquido a gas (vapor de agua).' },
  { id: 'quimica-9-11-03', level: '9-11', category: 'quimica', question: '¿De qué está hecha una molécula de agua?', options: ['Un átomo de oxígeno y uno de hidrógeno', 'Dos átomos de hidrógeno y uno de oxígeno', 'Tres átomos de oxígeno'], correctIndex: 1, explanation: 'El agua tiene la fórmula H₂O: dos átomos de hidrógeno unidos a un átomo de oxígeno.' },
  { id: 'quimica-9-11-04', level: '9-11', category: 'quimica', question: '¿Qué es el aire que respiramos?', options: ['Puro oxígeno', 'Una mezcla de gases, principalmente nitrógeno y oxígeno', 'Solo dióxido de carbono'], correctIndex: 1, explanation: 'El aire es sobre todo nitrógeno (78%) y oxígeno (21%), con pequeñas cantidades de otros gases.' },
  { id: 'quimica-9-11-05', level: '9-11', category: 'quimica', question: '¿Qué es la oxidación que forma el óxido (herrumbre) en el metal?', options: ['Una reacción entre el metal y el oxígeno del aire o el agua', 'Un tipo de pintura que se cae', 'El metal se derrite lentamente'], correctIndex: 0, explanation: 'Cuando el hierro entra en contacto con oxígeno y humedad, reacciona formando óxido, ese color café-rojizo.' },
  { id: 'quimica-9-11-06', level: '9-11', category: 'quimica', question: '¿Qué es un átomo?', options: ['La unidad más pequeña de un elemento que conserva sus propiedades químicas', 'Una molécula muy grande', 'Un tipo de célula'], correctIndex: 0, explanation: 'Los átomos son las piezas fundamentales que forman toda la materia; se combinan entre sí para formar moléculas.' },
  { id: 'quimica-9-11-07', level: '9-11', category: 'quimica', question: '¿Qué gas necesitan las plantas para hacer fotosíntesis?', options: ['Oxígeno', 'Dióxido de carbono', 'Nitrógeno'], correctIndex: 1, explanation: 'Las plantas absorben dióxido de carbono del aire y, con luz solar y agua, lo transforman en su alimento, liberando oxígeno.' },
  { id: 'quimica-9-11-08', level: '9-11', category: 'quimica', question: '¿Por qué se siente frío el hielo?', options: ['Porque quita calor a lo que toca', 'Porque emite frío como una energía propia', 'Porque está hecho de otro material que el agua'], correctIndex: 0, explanation: 'El "frío" que sentimos es en realidad que el hielo absorbe calor de nuestra piel; el calor siempre fluye de lo caliente a lo frío.' },
  { id: 'quimica-9-11-09', level: '9-11', category: 'quimica', question: '¿Qué pasa cuando mezclas vinagre con bicarbonato de sodio?', options: ['No pasa nada', 'Se produce una reacción que libera burbujas de dióxido de carbono', 'Se congela instantáneamente'], correctIndex: 1, explanation: 'El ácido del vinagre reacciona con el bicarbonato y libera gas CO₂, formando esa espuma burbujeante.' },
  { id: 'quimica-9-11-10', level: '9-11', category: 'quimica', question: '¿Qué es una sustancia soluble?', options: ['Una sustancia que se puede disolver en otra, como la sal en agua', 'Una sustancia que nunca cambia de estado', 'Un tipo de metal muy duro'], correctIndex: 0, explanation: 'Ser soluble significa poder disolverse y mezclarse uniformemente en otra sustancia, como ocurre con el azúcar o la sal en el agua.' },
];

if (typeof module !== 'undefined' && module.exports) module.exports = { QUESTIONS };
if (typeof window !== 'undefined') window.QUESTIONS = QUESTIONS;
