// rumbo-alfa-centauri/data.js
'use strict';

const QUESTIONS = [
  // --- Nivel 9-11 · Espacio y astronomía ---
  { id: 'espacio-9-11-01', level: '9-11', category: 'espacio', question: '¿Cuál es el planeta más cercano al Sol?', options: ['Venus', 'Mercurio', 'Marte'], correctIndex: 1, explanation: 'Mercurio es el planeta más cercano al Sol; tarda solo 88 días en darle la vuelta.' },
  { id: 'espacio-9-11-02', level: '9-11', category: 'espacio', question: '¿Qué astro ilumina la Tierra durante el día?', options: ['La Luna', 'El Sol', 'Una estrella lejana'], correctIndex: 1, explanation: 'El Sol es una estrella que emite su propia luz; la Luna solo refleja la luz del Sol.' },
  { id: 'espacio-9-11-03', level: '9-11', category: 'espacio', question: '¿Cómo se llama el planeta rojo?', options: ['Júpiter', 'Marte', 'Saturno'], correctIndex: 1, explanation: 'Marte se ve rojizo por el óxido de hierro en su superficie, el mismo compuesto que le da color al óxido de un metal.' },
  { id: 'espacio-9-11-04', level: '9-11', category: 'espacio', question: '¿Qué es un cometa?', options: ['Una estrella fugaz', 'Una bola de hielo y polvo que viaja por el espacio', 'Un satélite artificial'], correctIndex: 1, explanation: 'Los cometas son bolas de hielo, polvo y roca que dejan una cola brillante al acercarse al Sol.' },
  { id: 'espacio-9-11-05', level: '9-11', category: 'espacio', question: '¿Cuántos planetas hay en el sistema solar?', options: ['7', '8', '9'], correctIndex: 1, explanation: 'Son 8 desde que Plutón fue reclasificado como planeta enano en 2006.' },
  { id: 'espacio-9-11-06', level: '9-11', category: 'espacio', question: '¿Qué necesita un astronauta para respirar en el espacio?', options: ['Nada, hay aire', 'Un traje con oxígeno', 'Solo un casco'], correctIndex: 1, explanation: 'En el espacio no hay aire, así que los astronautas llevan oxígeno en su traje.' },
  { id: 'espacio-9-11-07', level: '9-11', category: 'espacio', question: '¿Qué es la Vía Láctea?', options: ['Un planeta', 'La galaxia donde vivimos', 'Una nave espacial'], correctIndex: 1, explanation: 'La Vía Láctea es la galaxia que contiene el Sol, la Tierra y miles de millones de estrellas más.' },
  { id: 'espacio-9-11-08', level: '9-11', category: 'espacio', question: '¿Por qué vemos diferentes fases de la Luna?', options: ['La Luna cambia de tamaño', 'Vemos distintas partes iluminadas por el Sol', 'Se apaga y se enciende'], correctIndex: 1, explanation: 'La Luna no emite luz propia; vemos distintas porciones iluminadas según su posición respecto al Sol y la Tierra.' },
  { id: 'espacio-9-11-09', level: '9-11', category: 'espacio', question: '¿Cuál es el planeta con más anillos visibles?', options: ['Saturno', 'Marte', 'Mercurio'], correctIndex: 0, explanation: 'Saturno tiene el sistema de anillos más grande y visible, hechos de hielo y roca.' },
  { id: 'espacio-9-11-10', level: '9-11', category: 'espacio', question: '¿Cuánto tarda la luz del Sol en llegar a la Tierra?', options: ['Unos 8 minutos', '1 segundo', '1 año'], correctIndex: 0, explanation: 'La luz viaja rapidísimo, pero el Sol está tan lejos que tarda unos 8 minutos en llegar a nosotros.' },

  // --- Nivel 9-11 · Física y naturaleza ---
  { id: 'fisica-9-11-01', level: '9-11', category: 'fisica', question: '¿Qué cae más rápido en la Luna: una pluma o un martillo?', options: ['La pluma', 'El martillo', 'Caen igual de rápido'], correctIndex: 2, explanation: 'En la Luna no hay aire que frene a la pluma, así que ambos caen a la misma velocidad por la gravedad lunar.' },
  { id: 'fisica-9-11-02', level: '9-11', category: 'fisica', question: '¿Por qué vemos un arcoíris después de la lluvia?', options: ['La luz del Sol se refleja y separa en colores al pasar por gotas de agua', 'El agua se pinta de colores', 'Es un reflejo de las nubes'], correctIndex: 0, explanation: 'Las gotas de agua actúan como pequeños prismas que separan la luz blanca del Sol en los colores que la forman.' },
  { id: 'fisica-9-11-03', level: '9-11', category: 'fisica', question: '¿Qué hace que un imán atraiga un clip de metal?', options: ['El calor', 'Un campo magnético invisible', 'La electricidad estática'], correctIndex: 1, explanation: 'Los imanes generan un campo magnético invisible que atrae materiales como el hierro y el acero.' },
  { id: 'fisica-9-11-04', level: '9-11', category: 'fisica', question: '¿Por qué flota un barco de metal en el agua si el metal es pesado?', options: ['Porque el agua es mágica', 'Porque su forma hueca desplaza suficiente agua para flotar', 'Porque va muy despacio'], correctIndex: 1, explanation: 'La forma hueca del barco hace que desplace un gran volumen de agua, generando suficiente empuje para flotar aunque el metal sea denso.' },
  { id: 'fisica-9-11-05', level: '9-11', category: 'fisica', question: '¿Qué es el sonido?', options: ['Luz que vibra', 'Vibraciones que viajan por el aire (u otro medio)', 'Un tipo de viento'], correctIndex: 1, explanation: 'El sonido son ondas de vibración que se propagan por el aire, el agua u otros materiales hasta llegar a nuestros oídos.' },
  { id: 'fisica-9-11-06', level: '9-11', category: 'fisica', question: '¿Por qué en el espacio no se escuchan sonidos?', options: ['Los astronautas están sordos por el casco', 'No hay aire (ni otro medio) para que el sonido viaje', 'Los sonidos son muy débiles'], correctIndex: 1, explanation: 'El sonido necesita un medio (como el aire) para propagarse; en el vacío del espacio no hay partículas que lo transmitan.' },
  { id: 'fisica-9-11-07', level: '9-11', category: 'fisica', question: '¿Qué fuerza te hace regresar al suelo cuando saltas?', options: ['El viento', 'La gravedad', 'La presión del aire'], correctIndex: 1, explanation: 'La gravedad de la Tierra atrae todo hacia su centro, por eso siempre regresamos al suelo después de saltar.' },
  { id: 'fisica-9-11-08', level: '9-11', category: 'fisica', question: '¿Por qué el hielo flota en el agua?', options: ['Porque es más frío', 'Porque es menos denso que el agua líquida', 'Porque el agua lo empuja hacia arriba con viento'], correctIndex: 1, explanation: 'Al congelarse, el agua forma una estructura con más espacio entre sus moléculas, haciéndola menos densa que el agua líquida.' },
  { id: 'fisica-9-11-09', level: '9-11', category: 'fisica', question: '¿Qué es un relámpago?', options: ['Una descarga eléctrica gigante entre nubes o hacia el suelo', 'Una explosión de aire caliente', 'Una estrella fugaz cercana'], correctIndex: 0, explanation: 'Es una enorme chispa de electricidad que se libera cuando se acumula suficiente carga eléctrica entre las nubes.' },
  { id: 'fisica-9-11-10', level: '9-11', category: 'fisica', question: '¿Por qué vemos el rayo antes de escuchar el trueno?', options: ['Porque el sonido viaja mucho más despacio que la luz', 'Porque el trueno ocurre después', 'Porque el rayo hace ruido primero'], correctIndex: 0, explanation: 'La luz viaja muchísimo más rápido que el sonido, así que vemos el destello casi al instante y el sonido del trueno llega segundos después.' },

  // --- Nivel 9-11 · Cuerpo humano y biología ---
  { id: 'biologia-9-11-01', level: '9-11', category: 'biologia', question: '¿Cuál es el órgano que bombea la sangre por todo el cuerpo?', options: ['El cerebro', 'El corazón', 'El estómago'], correctIndex: 1, explanation: 'El corazón es un músculo que late para impulsar la sangre a través de todo el cuerpo.' },
  { id: 'biologia-9-11-02', level: '9-11', category: 'biologia', question: '¿Cuántos huesos tiene aproximadamente el cuerpo de un adulto?', options: ['106', '206', '306'], correctIndex: 1, explanation: 'Un adulto tiene alrededor de 206 huesos (los bebés nacen con más, pero muchos se fusionan al crecer).' },
  { id: 'biologia-9-11-03', level: '9-11', category: 'biologia', question: '¿Qué órgano usamos principalmente para respirar?', options: ['Los pulmones', 'El hígado', 'Los riñones'], correctIndex: 0, explanation: 'Los pulmones absorben el oxígeno del aire y liberan dióxido de carbono cuando respiramos.' },
  { id: 'biologia-9-11-04', level: '9-11', category: 'biologia', question: '¿Para qué sirven los glóbulos rojos?', options: ['Combatir infecciones', 'Transportar oxígeno por el cuerpo', 'Digerir alimentos'], correctIndex: 1, explanation: 'Los glóbulos rojos contienen hemoglobina, que se une al oxígeno y lo lleva a todas las células del cuerpo.' },
  { id: 'biologia-9-11-05', level: '9-11', category: 'biologia', question: '¿Qué parte del cuerpo controla todos tus pensamientos y movimientos?', options: ['El corazón', 'El cerebro', 'El estómago'], correctIndex: 1, explanation: 'El cerebro es el centro de control del cuerpo: procesa la información y envía órdenes a través de los nervios.' },
  { id: 'biologia-9-11-06', level: '9-11', category: 'biologia', question: '¿Por qué necesitamos dormir?', options: ['Solo para pasar el tiempo', 'Para que el cuerpo y el cerebro descansen y se recuperen', 'Porque los ojos se cansan de ver'], correctIndex: 1, explanation: 'Durante el sueño, el cuerpo repara tejidos y el cerebro organiza la información aprendida durante el día.' },
  { id: 'biologia-9-11-07', level: '9-11', category: 'biologia', question: '¿Qué son los músculos?', options: ['Tejidos que se contraen para producir movimiento', 'Huesos flexibles', 'Parte del sistema digestivo'], correctIndex: 0, explanation: 'Los músculos se contraen y relajan para mover el cuerpo, desde caminar hasta parpadear.' },
  { id: 'biologia-9-11-08', level: '9-11', category: 'biologia', question: '¿Cuál es el órgano más grande del cuerpo humano?', options: ['El hígado', 'La piel', 'El cerebro'], correctIndex: 1, explanation: 'La piel cubre todo el cuerpo y protege contra gérmenes, regula la temperatura y nos da el sentido del tacto.' },
  { id: 'biologia-9-11-09', level: '9-11', category: 'biologia', question: '¿Qué le pasa a la comida en el estómago?', options: ['Se guarda sin cambios', 'Se mezcla con jugos gástricos que empiezan a descomponerla', 'Se convierte directo en energía'], correctIndex: 1, explanation: 'El estómago produce ácidos y jugos que descomponen la comida para que el cuerpo pueda absorber sus nutrientes.' },
  { id: 'biologia-9-11-10', level: '9-11', category: 'biologia', question: '¿Cuántos sentidos básicos solemos reconocer?', options: ['3', '5', '8'], correctIndex: 1, explanation: 'Los cinco sentidos clásicos son la vista, el oído, el olfato, el gusto y el tacto.' },

  // --- Nivel 9-11 · Química y materia ---
  { id: 'quimica-9-11-01', level: '9-11', category: 'quimica', question: '¿Cuáles son los tres estados básicos de la materia?', options: ['Sólido, líquido y gaseoso', 'Caliente, frío y templado', 'Duro, blando y suave'], correctIndex: 0, explanation: 'La materia puede existir en distintos estados según su temperatura y presión; los tres más comunes son sólido, líquido y gas.' },
  { id: 'quimica-9-11-02', level: '9-11', category: 'quimica', question: '¿Qué le pasa al agua cuando se calienta a 100°C al nivel del mar?', options: ['Se congela', 'Hierve y se convierte en vapor', 'Cambia de color'], correctIndex: 1, explanation: 'A 100°C, al nivel del mar, el agua alcanza su punto de ebullición y pasa de líquido a gas (vapor de agua).' },
  { id: 'quimica-9-11-03', level: '9-11', category: 'quimica', question: '¿De qué está hecha una molécula de agua?', options: ['Un átomo de oxígeno y uno de hidrógeno', 'Dos átomos de hidrógeno y uno de oxígeno', 'Tres átomos de oxígeno'], correctIndex: 1, explanation: 'El agua tiene la fórmula H₂O: dos átomos de hidrógeno unidos a un átomo de oxígeno.' },
  { id: 'quimica-9-11-04', level: '9-11', category: 'quimica', question: '¿Qué es el aire que respiramos?', options: ['Puro oxígeno', 'Una mezcla de gases, principalmente nitrógeno y oxígeno', 'Solo dióxido de carbono'], correctIndex: 1, explanation: 'El aire es sobre todo nitrógeno (78%) y oxígeno (21%), con pequeñas cantidades de otros gases.' },
  { id: 'quimica-9-11-05', level: '9-11', category: 'quimica', question: '¿Qué es la oxidación que forma el óxido (herrumbre) en el metal?', options: ['Una reacción entre el metal y el oxígeno del aire o el agua', 'Un tipo de pintura que se cae', 'El metal se derrite lentamente'], correctIndex: 0, explanation: 'Cuando el hierro entra en contacto con oxígeno y humedad, reacciona formando óxido, ese color café-rojizo.' },
  { id: 'quimica-9-11-06', level: '9-11', category: 'quimica', question: '¿Qué es un átomo?', options: ['La unidad más pequeña de un elemento que conserva sus propiedades químicas', 'Una molécula muy grande', 'Un tipo de célula'], correctIndex: 0, explanation: 'Los átomos son las piezas fundamentales que forman toda la materia; se combinan entre sí para formar moléculas.' },
  { id: 'quimica-9-11-07', level: '9-11', category: 'quimica', question: '¿Qué gas necesitan las plantas para hacer fotosíntesis?', options: ['Oxígeno', 'Dióxido de carbono', 'Nitrógeno'], correctIndex: 1, explanation: 'Las plantas absorben dióxido de carbono del aire y, con luz solar y agua, lo transforman en su alimento, liberando oxígeno.' },
  { id: 'quimica-9-11-08', level: '9-11', category: 'quimica', question: '¿Por qué se siente frío el hielo?', options: ['Porque quita calor a lo que toca', 'Porque emite frío como una energía propia', 'Porque está hecho de otro material que el agua'], correctIndex: 0, explanation: 'El "frío" que sentimos es en realidad que el hielo absorbe calor de nuestra piel; el calor siempre fluye de lo caliente a lo frío.' },
  { id: 'quimica-9-11-09', level: '9-11', category: 'quimica', question: '¿Qué pasa cuando mezclas vinagre con bicarbonato de sodio?', options: ['No pasa nada', 'Se produce una reacción que libera burbujas de dióxido de carbono', 'Se congela instantáneamente'], correctIndex: 1, explanation: 'El ácido del vinagre reacciona con el bicarbonato y libera gas CO₂, formando esa espuma burbujeante.' },
  { id: 'quimica-9-11-10', level: '9-11', category: 'quimica', question: '¿Qué es una sustancia soluble?', options: ['Una sustancia que se puede disolver en otra, como la sal en agua', 'Una sustancia que nunca cambia de estado', 'Un tipo de metal muy duro'], correctIndex: 0, explanation: 'Ser soluble significa poder disolverse y mezclarse uniformemente en otra sustancia, como ocurre con el azúcar o la sal en el agua.' },

  // --- Nivel 12-15 · Espacio y astronomía ---
  { id: 'espacio-12-15-01', level: '12-15', category: 'espacio', question: '¿Qué fuerza mantiene a los planetas en órbita alrededor del Sol?', options: ['El magnetismo', 'La gravedad', 'La presión atmosférica'], correctIndex: 1, explanation: 'La gravedad del Sol atrae a los planetas y los mantiene en órbita en vez de salir disparados al espacio.' },
  { id: 'espacio-12-15-02', level: '12-15', category: 'espacio', question: '¿Qué es una supernova?', options: ['El nacimiento de una estrella', 'La explosión final de una estrella masiva', 'Un tipo de agujero negro'], correctIndex: 1, explanation: 'Una supernova es la explosión violenta que ocurre cuando una estrella masiva agota su combustible nuclear.' },
  { id: 'espacio-12-15-03', level: '12-15', category: 'espacio', question: '¿Qué es un año luz?', options: ['El tiempo que tarda la Tierra en dar la vuelta al Sol', 'La distancia que recorre la luz en un año', 'El tiempo que dura un día en otro planeta'], correctIndex: 1, explanation: 'Un año luz mide distancia, no tiempo: es lo que la luz recorre en un año (unos 9.46 billones de km).' },
  { id: 'espacio-12-15-04', level: '12-15', category: 'espacio', question: '¿Por qué Marte parece rojo?', options: ['Por el reflejo del Sol', 'Por óxido de hierro en su superficie', 'Por su atmósfera de metano'], correctIndex: 1, explanation: 'El polvo de la superficie marciana contiene óxido de hierro, el mismo compuesto que le da color al óxido.' },
  { id: 'espacio-12-15-05', level: '12-15', category: 'espacio', question: '¿Qué es un agujero negro?', options: ['Una región vacía del espacio', 'Una región con gravedad tan intensa que ni la luz escapa', 'Un planeta sin atmósfera'], correctIndex: 1, explanation: 'Un agujero negro tiene una gravedad tan fuerte que atrapa incluso la luz, por eso no se puede ver directamente.' },
  { id: 'espacio-12-15-06', level: '12-15', category: 'espacio', question: '¿Cuál es la estrella más cercana a la Tierra después del Sol?', options: ['Sirio', 'Próxima Centauri', 'Polaris'], correctIndex: 1, explanation: 'Próxima Centauri, parte del sistema de Alfa Centauri, está a unos 4.2 años luz de distancia.' },
  { id: 'espacio-12-15-07', level: '12-15', category: 'espacio', question: '¿Qué causa las mareas en la Tierra?', options: ['El viento solar', 'La atracción gravitacional de la Luna (y el Sol)', 'La rotación terrestre'], correctIndex: 1, explanation: 'La gravedad de la Luna (con ayuda del Sol) atrae el agua de los océanos y genera las mareas.' },
  { id: 'espacio-12-15-08', level: '12-15', category: 'espacio', question: '¿Por qué los astronautas flotan dentro de la Estación Espacial Internacional?', options: ['Porque no hay gravedad en el espacio', 'Porque están en caída libre constante alrededor de la Tierra', 'Porque el traje los hace flotar'], correctIndex: 1, explanation: 'Sí hay gravedad ahí; la estación y todo dentro de ella están en caída libre continua mientras orbitan la Tierra, lo que se siente como ingravidez.' },
  { id: 'espacio-12-15-09', level: '12-15', category: 'espacio', question: '¿Qué es una galaxia espiral?', options: ['Una galaxia con forma de disco y brazos curvos, como la Vía Láctea', 'Una galaxia sin estrellas', 'Una nube de gas sin forma'], correctIndex: 0, explanation: 'Las galaxias espirales tienen un núcleo brillante y brazos curvos llenos de estrellas, gas y polvo.' },
  { id: 'espacio-12-15-10', level: '12-15', category: 'espacio', question: '¿Qué es la heliopausa?', options: ['El borde del sistema solar donde el viento solar deja de dominar', 'La capa más caliente del Sol', 'La órbita de Plutón'], correctIndex: 0, explanation: 'Es la frontera donde la influencia del viento solar cede ante el espacio interestelar.' },

  // --- Nivel 12-15 · Física y naturaleza ---
  { id: 'fisica-12-15-01', level: '12-15', category: 'fisica', question: '¿Qué establece la primera ley de Newton (ley de la inercia)?', options: ['Un objeto en reposo o en movimiento sigue así a menos que una fuerza actúe sobre él', 'La fuerza es igual a masa por aceleración', 'Toda acción tiene una reacción igual y opuesta'], correctIndex: 0, explanation: 'La inercia describe la tendencia de los objetos a mantener su estado de movimiento (o reposo) salvo que una fuerza externa los cambie.' },
  { id: 'fisica-12-15-02', level: '12-15', category: 'fisica', question: '¿Qué tipo de energía almacena una liga estirada?', options: ['Energía cinética', 'Energía potencial elástica', 'Energía térmica'], correctIndex: 1, explanation: 'La energía potencial elástica se almacena en objetos deformados, como una liga estirada o un resorte comprimido, y se libera al soltarlos.' },
  { id: 'fisica-12-15-03', level: '12-15', category: 'fisica', question: '¿Por qué el cielo se ve azul de día?', options: ['Porque el aire es azul', 'Porque la atmósfera dispersa más la luz azul que otros colores', 'Porque refleja el color del mar'], correctIndex: 1, explanation: 'La luz azul tiene una longitud de onda corta que se dispersa más al chocar con las moléculas del aire, un fenómeno llamado dispersión de Rayleigh.' },
  { id: 'fisica-12-15-04', level: '12-15', category: 'fisica', question: '¿Qué es la velocidad terminal de un objeto que cae?', options: ['La velocidad máxima al tocar el suelo', 'La velocidad constante que alcanza cuando la resistencia del aire iguala a la gravedad', 'La velocidad inicial de la caída'], correctIndex: 1, explanation: 'Cuando la fuerza de fricción del aire iguala al peso del objeto, este deja de acelerar y cae a velocidad constante.' },
  { id: 'fisica-12-15-05', level: '12-15', category: 'fisica', question: '¿Qué principio explica por qué un avión se mantiene en el aire?', options: ['La diferencia de presión que genera sustentación en las alas', 'El empuje de los motores empujando hacia arriba', 'La forma redonda del fuselaje'], correctIndex: 0, explanation: 'El diseño de las alas genera una diferencia de presión entre la parte superior e inferior que produce una fuerza de sustentación hacia arriba.' },
  { id: 'fisica-12-15-06', level: '12-15', category: 'fisica', question: '¿Qué es la refracción de la luz?', options: ['El rebote de la luz en una superficie', 'El cambio de dirección de la luz al pasar de un medio a otro', 'La absorción total de la luz'], correctIndex: 1, explanation: 'La luz cambia de velocidad y de dirección al pasar, por ejemplo, del aire al agua, lo que causa efectos como que un popote se vea "quebrado" en un vaso.' },
  { id: 'fisica-12-15-07', level: '12-15', category: 'fisica', question: '¿Qué es la conservación de la energía?', options: ['La energía se puede crear si se usa una máquina potente', 'La energía no se crea ni se destruye, solo se transforma', 'La energía siempre disminuye con el tiempo'], correctIndex: 1, explanation: 'En un sistema cerrado, la energía total permanece constante; solo cambia de una forma a otra (por ejemplo, de potencial a cinética).' },
  { id: 'fisica-12-15-08', level: '12-15', category: 'fisica', question: '¿Por qué patinar sobre hielo tiene tan poca fricción?', options: ['Porque el hielo es un material especial que repele todo', 'Porque una fina capa de agua se forma bajo la cuchilla, reduciendo la fricción', 'Porque el frío detiene la fricción'], correctIndex: 1, explanation: 'La presión y el roce de la cuchilla generan una delgada película de agua que actúa como lubricante entre el metal y el hielo.' },
  { id: 'fisica-12-15-09', level: '12-15', category: 'fisica', question: '¿Qué mide la escala de Richter?', options: ['La temperatura de un terremoto', 'La magnitud (energía liberada) de un terremoto', 'La profundidad del epicentro'], correctIndex: 1, explanation: 'Mide la energía liberada por un sismo; cada punto completo representa una liberación de energía mucho mayor que el anterior.' },
  { id: 'fisica-12-15-10', level: '12-15', category: 'fisica', question: '¿Qué es el efecto Doppler?', options: ['El cambio aparente de frecuencia de una onda cuando la fuente se mueve respecto al observador', 'Un tipo de eco', 'La pérdida de energía del sonido con la distancia'], correctIndex: 0, explanation: 'Por eso la sirena de una ambulancia suena más aguda cuando se acerca y más grave cuando se aleja: la frecuencia de la onda percibida cambia con el movimiento relativo.' },

  // --- Nivel 12-15 · Cuerpo humano y biología ---
  { id: 'biologia-12-15-01', level: '12-15', category: 'biologia', question: '¿Qué función cumplen los riñones?', options: ['Producir hormonas del crecimiento', 'Filtrar la sangre y eliminar desechos en forma de orina', 'Almacenar oxígeno'], correctIndex: 1, explanation: 'Los riñones filtran la sangre constantemente, eliminando toxinas y exceso de líquido que se expulsan como orina.' },
  { id: 'biologia-12-15-02', level: '12-15', category: 'biologia', question: '¿Qué es el sistema inmunológico?', options: ['El conjunto de órganos que digieren la comida', 'La red de defensas del cuerpo contra infecciones y enfermedades', 'El sistema que controla los músculos'], correctIndex: 1, explanation: 'Incluye glóbulos blancos, anticuerpos y otros mecanismos que identifican y combaten patógenos como virus y bacterias.' },
  { id: 'biologia-12-15-03', level: '12-15', category: 'biologia', question: '¿Qué es el ADN?', options: ['Una proteína que da energía a las células', 'La molécula que contiene las instrucciones genéticas de un ser vivo', 'Un tipo de vitamina'], correctIndex: 1, explanation: 'El ADN (ácido desoxirribonucleico) guarda el "manual de instrucciones" que determina las características de cada ser vivo.' },
  { id: 'biologia-12-15-04', level: '12-15', category: 'biologia', question: '¿Qué hacen las neuronas?', options: ['Transportan oxígeno por el cuerpo', 'Transmiten señales eléctricas y químicas por el sistema nervioso', 'Producen glóbulos rojos'], correctIndex: 1, explanation: 'Las neuronas se comunican entre sí mediante impulsos eléctricos y sustancias químicas, permitiendo pensar, sentir y moverse.' },
  { id: 'biologia-12-15-05', level: '12-15', category: 'biologia', question: '¿Qué es la homeostasis?', options: ['La capacidad del cuerpo de mantener condiciones internas estables (como la temperatura)', 'El proceso de crecimiento óseo', 'La producción de hormonas del sueño'], correctIndex: 0, explanation: 'El cuerpo regula constantemente variables internas —temperatura, pH, glucosa— para mantenerlas dentro de un rango estable pese a cambios externos.' },
  { id: 'biologia-12-15-06', level: '12-15', category: 'biologia', question: '¿Cuál es la función principal de las plaquetas en la sangre?', options: ['Transportar oxígeno', 'Ayudar a que la sangre coagule y cierre heridas', 'Combatir virus'], correctIndex: 1, explanation: 'Las plaquetas se agrupan en el sitio de una herida para formar un coágulo y detener el sangrado.' },
  { id: 'biologia-12-15-07', level: '12-15', category: 'biologia', question: '¿Qué diferencia hay entre arterias y venas?', options: ['Las arterias llevan sangre desde el corazón y las venas la regresan hacia el corazón', 'Son exactamente lo mismo', 'Las venas solo existen en las piernas'], correctIndex: 0, explanation: 'Las arterias transportan sangre (generalmente oxigenada) desde el corazón hacia el cuerpo, y las venas la regresan de vuelta al corazón.' },
  { id: 'biologia-12-15-08', level: '12-15', category: 'biologia', question: '¿Qué es una vacuna?', options: ['Un medicamento que cura enfermedades ya presentes', 'Una preparación que entrena al sistema inmunológico para reconocer un patógeno antes de una infección real', 'Un tipo de antibiótico'], correctIndex: 1, explanation: 'Las vacunas exponen al cuerpo a una versión debilitada, inactiva o parcial de un patógeno para que el sistema inmune aprenda a defenderse sin causar la enfermedad completa.' },
  { id: 'biologia-12-15-09', level: '12-15', category: 'biologia', question: '¿Qué órgano produce la insulina?', options: ['El páncreas', 'El hígado', 'El bazo'], correctIndex: 0, explanation: 'El páncreas produce insulina, una hormona que regula los niveles de azúcar (glucosa) en la sangre.' },
  { id: 'biologia-12-15-10', level: '12-15', category: 'biologia', question: '¿Qué es una mutación genética?', options: ['Un cambio en la secuencia del ADN', 'Una enfermedad contagiosa', 'Un tipo de vacuna'], correctIndex: 0, explanation: 'Una mutación es un cambio en el ADN que puede ser heredado, causado por errores al copiarse o por factores externos; algunas son neutrales, otras dañinas y otras beneficiosas.' },

  // --- Nivel 12-15 · Química y materia ---
  { id: 'quimica-12-15-01', level: '12-15', category: 'quimica', question: '¿Qué es un elemento químico?', options: ['Una sustancia formada por un solo tipo de átomo', 'Cualquier mezcla de sustancias', 'Solo los metales de la tabla periódica'], correctIndex: 0, explanation: 'Un elemento está compuesto únicamente por átomos del mismo número atómico, como el oxígeno o el hierro; no puede descomponerse en sustancias más simples por medios químicos.' },
  { id: 'quimica-12-15-02', level: '12-15', category: 'quimica', question: '¿Qué indica el número atómico de un elemento?', options: ['El número de protones en su núcleo', 'El número total de partículas', 'Su peso en gramos'], correctIndex: 0, explanation: 'El número atómico es la cantidad de protones en el núcleo, y es lo que define de qué elemento se trata.' },
  { id: 'quimica-12-15-03', level: '12-15', category: 'quimica', question: '¿Qué diferencia hay entre un compuesto y una mezcla?', options: ['Un compuesto tiene sus elementos unidos químicamente en proporciones fijas; una mezcla no', 'Son exactamente lo mismo', 'Un compuesto siempre es un gas'], correctIndex: 0, explanation: 'En un compuesto (como el agua, H₂O), los elementos están unidos químicamente en proporciones exactas; en una mezcla (como el aire o una ensalada) los componentes conservan sus propiedades y se pueden separar físicamente.' },
  { id: 'quimica-12-15-04', level: '12-15', category: 'quimica', question: '¿Qué es el pH y qué mide?', options: ['Mide qué tan ácida o básica (alcalina) es una sustancia', 'Mide la temperatura de una sustancia', 'Mide la densidad de un líquido'], correctIndex: 0, explanation: 'La escala de pH va de 0 (muy ácido) a 14 (muy básico), con 7 como neutro (el agua pura, por ejemplo).' },
  { id: 'quimica-12-15-05', level: '12-15', category: 'quimica', question: '¿Qué es una reacción exotérmica?', options: ['Una reacción que absorbe calor del entorno', 'Una reacción que libera calor al entorno', 'Una reacción que no involucra energía'], correctIndex: 1, explanation: 'En una reacción exotérmica, como la combustión, se libera energía en forma de calor hacia el entorno.' },
  { id: 'quimica-12-15-06', level: '12-15', category: 'quimica', question: '¿Qué son los isótopos?', options: ['Átomos del mismo elemento con distinto número de neutrones', 'Elementos completamente diferentes', 'Moléculas de agua modificadas'], correctIndex: 0, explanation: 'Los isótopos comparten el mismo número de protones (mismo elemento) pero difieren en el número de neutrones, lo que cambia su masa atómica.' },
  { id: 'quimica-12-15-07', level: '12-15', category: 'quimica', question: '¿Qué ley química establece que la materia no se crea ni se destruye en una reacción, solo se transforma?', options: ['Ley de conservación de la masa', 'Ley de los gases ideales', 'Ley periódica'], correctIndex: 0, explanation: 'Propuesta por Lavoisier: en una reacción química cerrada, la masa total de los reactivos es igual a la masa total de los productos.' },
  { id: 'quimica-12-15-08', level: '12-15', category: 'quimica', question: '¿Qué son los enlaces covalentes?', options: ['Enlaces donde los átomos comparten electrones', 'Enlaces donde un átomo cede electrones por completo a otro', 'Enlaces que solo existen en metales'], correctIndex: 0, explanation: 'En un enlace covalente, dos átomos comparten uno o más pares de electrones, como ocurre entre los átomos de hidrógeno y oxígeno en el agua.' },
  { id: 'quimica-12-15-09', level: '12-15', category: 'quimica', question: '¿Qué distingue a un catalizador en una reacción química?', options: ['Acelera la reacción sin consumirse en el proceso', 'Detiene por completo cualquier reacción', 'Cambia el color de los productos siempre'], correctIndex: 0, explanation: 'Un catalizador reduce la energía necesaria para que ocurra una reacción, acelerándola, pero al final del proceso permanece químicamente inalterado.' },
  { id: 'quimica-12-15-10', level: '12-15', category: 'quimica', question: '¿Qué es el plasma como estado de la materia?', options: ['Un cuarto estado de la materia con gas ionizado a muy alta energía', 'Un tipo de líquido espeso', 'Un sólido transparente'], correctIndex: 0, explanation: 'El plasma es un gas al que se le ha dado tanta energía que sus átomos pierden electrones, formando una mezcla de iones y electrones libres; el Sol y los rayos son ejemplos de plasma.' },

  // --- Nivel adulto · Espacio y astronomía ---
  { id: 'espacio-adulto-01', level: 'adulto', category: 'espacio', question: '¿Qué mecanismo produce la fusión nuclear que hace brillar al Sol?', options: ['Fusión de hidrógeno en helio', 'Fisión de uranio', 'Combustión química'], correctIndex: 0, explanation: 'En el núcleo solar, átomos de hidrógeno se fusionan bajo presión y temperatura extremas para formar helio, liberando energía.' },
  { id: 'espacio-adulto-02', level: 'adulto', category: 'espacio', question: '¿Qué es el redshift (corrimiento al rojo) cosmológico?', options: ['El cambio de color de una estrella al enfriarse', 'El estiramiento de la luz hacia longitudes de onda mayores por la expansión del universo', 'Un efecto óptico de la atmósfera terrestre'], correctIndex: 1, explanation: 'Cuando el universo se expande, la luz de galaxias lejanas se estira hacia el rojo; a mayor distancia, mayor corrimiento.' },
  { id: 'espacio-adulto-03', level: 'adulto', category: 'espacio', question: '¿Qué predice la relatividad general sobre la luz cerca de objetos masivos?', options: ['Que se curva por la gravedad', 'Que se acelera', 'Que cambia de color permanentemente'], correctIndex: 0, explanation: 'La masa curva el espacio-tiempo, y la luz sigue esa curvatura; es la base del fenómeno de lente gravitacional.' },
  { id: 'espacio-adulto-04', level: 'adulto', category: 'espacio', question: '¿Qué es un exoplaneta?', options: ['Un planeta enano dentro del sistema solar', 'Un planeta que orbita una estrella distinta al Sol', 'Un asteroide con atmósfera'], correctIndex: 1, explanation: 'Un exoplaneta orbita una estrella fuera de nuestro sistema solar; se han confirmado miles con telescopios como Kepler y TESS.' },
  { id: 'espacio-adulto-05', level: 'adulto', category: 'espacio', question: '¿Cómo se detecta la mayoría de los exoplanetas conocidos?', options: ['Fotografiándolos directamente', 'Por el método de tránsito (la caída de brillo cuando pasan frente a su estrella)', 'Por radar'], correctIndex: 1, explanation: 'El método de tránsito mide pequeñas disminuciones de brillo estelar cuando un planeta pasa por delante de su estrella.' },
  { id: 'espacio-adulto-06', level: 'adulto', category: 'espacio', question: '¿Qué es la materia oscura?', options: ['Materia que no emite ni refleja luz pero cuya gravedad se detecta en galaxias', 'Agujeros negros pequeños', 'Antimateria residual del Big Bang'], correctIndex: 0, explanation: 'No se observa directamente, pero su efecto gravitacional explica por qué las galaxias giran más rápido de lo esperado con la materia visible.' },
  { id: 'espacio-adulto-07', level: 'adulto', category: 'espacio', question: '¿Qué tan lejos está el sistema de Alfa Centauri de la Tierra?', options: ['Unos 4.37 años luz', '400 años luz', '40,000 años luz'], correctIndex: 0, explanation: 'Es el sistema estelar más cercano al Sol, a unos 4.37 años luz, aunque sigue siendo un viaje de miles de años con la tecnología actual.' },
  { id: 'espacio-adulto-08', level: 'adulto', category: 'espacio', question: '¿Qué es una enana blanca?', options: ['Una estrella joven pequeña', 'El núcleo remanente de una estrella tras agotar su combustible', 'Un tipo de planeta helado'], correctIndex: 1, explanation: 'Es lo que queda del núcleo de una estrella como el Sol cuando se apagan sus reacciones nucleares; es extremadamente densa.' },
  { id: 'espacio-adulto-09', level: 'adulto', category: 'espacio', question: '¿Qué evidencia respalda la teoría del Big Bang?', options: ['La radiación cósmica de fondo de microondas', 'Las manchas solares', 'Los anillos de Saturno'], correctIndex: 0, explanation: 'Esa radiación es el "resplandor" remanente del universo temprano, descubierta en 1965, y es una de las pruebas más fuertes del Big Bang.' },
  { id: 'espacio-adulto-10', level: 'adulto', category: 'espacio', question: '¿Qué distingue a una estrella de neutrones?', options: ['Es una estrella hecha completamente de neutrones extremadamente densa, remanente de una supernova', 'Es una estrella recién nacida', 'Es una nube de gas antes de formar estrellas'], correctIndex: 0, explanation: 'Se forma al colapsar el núcleo de una estrella masiva en una supernova; una cucharadita de su materia pesaría miles de millones de toneladas.' },

  // --- Nivel adulto · Física y naturaleza ---
  { id: 'fisica-adulto-01', level: 'adulto', category: 'fisica', question: '¿Qué establece la segunda ley de la termodinámica?', options: ['La energía siempre se conserva perfectamente', 'La entropía de un sistema aislado tiende a aumentar con el tiempo', 'El calor siempre fluye de frío a caliente'], correctIndex: 1, explanation: 'En un sistema aislado, el desorden (entropía) tiende a aumentar; por eso el calor fluye espontáneamente de caliente a frío y no al revés.' },
  { id: 'fisica-adulto-02', level: 'adulto', category: 'fisica', question: '¿Qué fenómeno cuántico permite que una partícula atraviese una barrera que clásicamente no podría cruzar?', options: ['Efecto fotoeléctrico', 'Efecto túnel', 'Superconductividad'], correctIndex: 1, explanation: 'El efecto túnel cuántico permite que partículas atraviesen barreras de energía que, según la física clásica, serían infranqueables.' },
  { id: 'fisica-adulto-03', level: 'adulto', category: 'fisica', question: '¿Qué describe el principio de incertidumbre de Heisenberg?', options: ['No se puede conocer con precisión absoluta la posición y el momento de una partícula simultáneamente', 'No se puede medir la temperatura exacta de un gas', 'La luz siempre viaja a la misma velocidad'], correctIndex: 0, explanation: 'Cuanta más precisión se tiene sobre la posición de una partícula, menos se puede conocer sobre su momento (y viceversa); es una propiedad fundamental de la naturaleza, no una limitación del instrumento.' },
  { id: 'fisica-adulto-04', level: 'adulto', category: 'fisica', question: '¿Qué es un superconductor?', options: ['Un material que conduce electricidad sin resistencia por debajo de cierta temperatura crítica', 'Un metal que nunca se calienta', 'Un aislante perfecto'], correctIndex: 0, explanation: 'Al enfriarse por debajo de su temperatura crítica, ciertos materiales pierden toda resistencia eléctrica y pueden conducir corriente indefinidamente sin perder energía.' },
  { id: 'fisica-adulto-05', level: 'adulto', category: 'fisica', question: '¿Qué establece la ecuación E=mc²?', options: ['La energía es igual a la masa por la velocidad de la luz al cuadrado', 'La masa se pierde con el tiempo', 'La velocidad de la luz depende de la masa'], correctIndex: 0, explanation: 'Einstein demostró que masa y energía son equivalentes: una pequeña cantidad de masa puede convertirse en una enorme cantidad de energía.' },
  { id: 'fisica-adulto-06', level: 'adulto', category: 'fisica', question: '¿Qué son las ondas gravitacionales, detectadas por primera vez en 2015?', options: ['Ondas de sonido en el espacio', 'Perturbaciones en el espacio-tiempo causadas por eventos masivos, como la fusión de agujeros negros', 'Ondas de radio de origen desconocido'], correctIndex: 1, explanation: 'Son "arrugas" en el tejido del espacio-tiempo predichas por Einstein, producidas por eventos cósmicos extremadamente violentos.' },
  { id: 'fisica-adulto-07', level: 'adulto', category: 'fisica', question: '¿Qué es el cero absoluto?', options: ['La temperatura más fría posible, donde cesa el movimiento térmico de las partículas', '0 grados Celsius', 'La temperatura del espacio exterior'], correctIndex: 0, explanation: 'Es el límite teórico de temperatura (-273.15°C) donde las partículas tendrían la mínima energía térmica posible.' },
  { id: 'fisica-adulto-08', level: 'adulto', category: 'fisica', question: '¿Qué explica la dualidad onda-partícula?', options: ['Que la luz y la materia pueden comportarse como ondas o como partículas según el experimento', 'Que hay dos tipos de luz distintos', 'Que las partículas siempre viajan en pares'], correctIndex: 0, explanation: 'Fenómenos como la luz o los electrones muestran propiedades de onda (interferencia) y de partícula (colisiones) dependiendo de cómo se observen.' },
  { id: 'fisica-adulto-09', level: 'adulto', category: 'fisica', question: '¿Qué es un superfluido?', options: ['Un líquido que fluye sin viscosidad alguna', 'Un gas muy denso', 'Un sólido que se comporta como líquido al calentarse'], correctIndex: 0, explanation: 'Ciertos materiales, como el helio a temperaturas extremadamente bajas, fluyen sin ninguna fricción interna, un efecto puramente cuántico.' },
  { id: 'fisica-adulto-10', level: 'adulto', category: 'fisica', question: '¿Qué mide el número de Reynolds en dinámica de fluidos?', options: ['La temperatura del fluido', 'La relación entre fuerzas inerciales y viscosas, que predice si un flujo será laminar o turbulento', 'La presión atmosférica'], correctIndex: 1, explanation: 'Un número de Reynolds bajo indica flujo laminar (ordenado) y uno alto indica flujo turbulento (caótico); es clave en aerodinámica e ingeniería.' },

  // --- Nivel adulto · Cuerpo humano y biología ---
  { id: 'biologia-adulto-01', level: 'adulto', category: 'biologia', question: '¿Qué es la apoptosis?', options: ['La muerte celular programada, un proceso normal y necesario del cuerpo', 'La división descontrolada de células cancerosas', 'La formación de nuevos vasos sanguíneos'], correctIndex: 0, explanation: 'La apoptosis elimina células dañadas o innecesarias de forma controlada, sin dañar el tejido circundante, y es esencial para el desarrollo y mantenimiento del cuerpo.' },
  { id: 'biologia-adulto-02', level: 'adulto', category: 'biologia', question: '¿Qué es la microbiota intestinal?', options: ['Un tipo de parásito dañino', 'El conjunto de microorganismos que viven en el intestino y ayudan a la digestión e inmunidad', 'Una enfermedad del colon'], correctIndex: 1, explanation: 'Billones de bacterias y otros microorganismos habitan el intestino, ayudando a digerir alimentos, producir vitaminas y regular el sistema inmune.' },
  { id: 'biologia-adulto-03', level: 'adulto', category: 'biologia', question: '¿Qué diferencia hay entre inmunidad innata e inmunidad adaptativa?', options: ['La innata es una respuesta rápida y general; la adaptativa es específica y genera memoria', 'Son exactamente lo mismo', 'La adaptativa solo actúa en la piel'], correctIndex: 0, explanation: 'La inmunidad innata reacciona de inmediato ante cualquier invasor; la adaptativa tarda más en activarse pero reconoce patógenos específicos y "recuerda" para responder más rápido en el futuro.' },
  { id: 'biologia-adulto-04', level: 'adulto', category: 'biologia', question: '¿Qué es la epigenética?', options: ['El estudio de cambios heredables en la expresión de los genes sin alterar la secuencia del ADN', 'Un tipo de mutación genética permanente', 'La clonación de organismos'], correctIndex: 0, explanation: 'Factores ambientales pueden "activar" o "silenciar" genes sin cambiar el ADN en sí, y estos cambios a veces se transmiten a la siguiente generación.' },
  { id: 'biologia-adulto-05', level: 'adulto', category: 'biologia', question: '¿Qué función cumple la barrera hematoencefálica?', options: ['Filtra la sangre en los riñones', 'Protege al cerebro regulando qué sustancias pasan de la sangre al tejido cerebral', 'Produce líquido cefalorraquídeo'], correctIndex: 1, explanation: 'Esta barrera selectiva protege al cerebro de toxinas y patógenos, pero también dificulta que ciertos medicamentos lleguen al sistema nervioso central.' },
  { id: 'biologia-adulto-06', level: 'adulto', category: 'biologia', question: '¿Qué son las células madre?', options: ['Células especializadas que ya no pueden cambiar', 'Células con capacidad de convertirse en distintos tipos de células especializadas', 'Células muertas que el cuerpo elimina'], correctIndex: 1, explanation: 'Las células madre pueden diferenciarse en diversos tipos celulares (musculares, nerviosas, sanguíneas), lo que las hace clave en el desarrollo y la medicina regenerativa.' },
  { id: 'biologia-adulto-07', level: 'adulto', category: 'biologia', question: '¿Qué es la resistencia a los antibióticos?', options: ['Cuando el cuerpo humano se vuelve inmune a las bacterias', 'Cuando las bacterias evolucionan mecanismos para sobrevivir a los antibióticos que antes las eliminaban', 'Una alergia a los medicamentos'], correctIndex: 1, explanation: 'El uso excesivo o incorrecto de antibióticos favorece que las bacterias más resistentes sobrevivan y se reproduzcan, haciendo que esos medicamentos pierdan eficacia con el tiempo.' },
  { id: 'biologia-adulto-08', level: 'adulto', category: 'biologia', question: '¿Qué es la neuroplasticidad?', options: ['La capacidad del cerebro de reorganizarse y formar nuevas conexiones a lo largo de la vida', 'La rigidez del cerebro tras cierta edad', 'Un tipo de enfermedad neurológica'], correctIndex: 0, explanation: 'El cerebro puede formar y reorganizar conexiones sinápticas en respuesta al aprendizaje, la experiencia o incluso una lesión, incluso en la edad adulta.' },
  { id: 'biologia-adulto-09', level: 'adulto', category: 'biologia', question: '¿Qué papel juegan los telómeros en el envejecimiento celular?', options: ['Protegen los extremos de los cromosomas y se acortan con cada división celular', 'Producen hormonas del crecimiento', 'Almacenan energía en la célula'], correctIndex: 0, explanation: 'Los telómeros actúan como una "cuenta regresiva" protectora en el ADN; su acortamiento progresivo se asocia con el envejecimiento y el límite de divisiones de una célula.' },
  { id: 'biologia-adulto-10', level: 'adulto', category: 'biologia', question: '¿Qué es el efecto placebo?', options: ['Una mejora real medible causada por un tratamiento sin principio activo, debido a la expectativa del paciente', 'Un tipo de enfermedad psicológica', 'Un fallo en el diagnóstico médico'], correctIndex: 0, explanation: 'Aunque no contiene ningún ingrediente activo, un placebo puede producir mejoras reales gracias a mecanismos psicológicos y neurobiológicos ligados a la expectativa de mejorar.' },

  // --- Nivel adulto · Química y materia ---
  { id: 'quimica-adulto-01', level: 'adulto', category: 'quimica', question: '¿Qué principio explica por qué el agua tiene una densidad máxima a 4°C en lugar de en su punto de congelación?', options: ['La estructura cristalina que forma el hielo al congelarse ocupa más espacio que el agua líquida cercana a 4°C', 'El agua se contamina a esa temperatura', 'Es un error de medición común'], correctIndex: 0, explanation: 'Cerca de 4°C el agua alcanza su densidad máxima; al seguir enfriándose hacia 0°C, las moléculas empiezan a organizarse en la estructura hexagonal del hielo, que ocupa más volumen y por eso es menos densa (flota).' },
  { id: 'quimica-adulto-02', level: 'adulto', category: 'quimica', question: '¿Qué es la entalpía en termoquímica?', options: ['Una medida del contenido de calor de un sistema a presión constante', 'La velocidad de una reacción', 'La masa molar de un compuesto'], correctIndex: 0, explanation: 'La entalpía cuantifica la energía calorífica que un sistema intercambia con su entorno durante un proceso a presión constante.' },
  { id: 'quimica-adulto-03', level: 'adulto', category: 'quimica', question: '¿Qué caracteriza a una reacción en equilibrio químico?', options: ['Los reactivos y productos dejan de reaccionar por completo', 'Las velocidades de la reacción directa e inversa se igualan, aunque ambas sigan ocurriendo', 'Toda la sustancia se convierte en producto'], correctIndex: 1, explanation: 'En el equilibrio, la reacción no se detiene: las reacciones directa e inversa ocurren a la misma velocidad, por lo que las concentraciones netas permanecen constantes.' },
  { id: 'quimica-adulto-04', level: 'adulto', category: 'quimica', question: '¿Qué es un compuesto anfótero?', options: ['Una sustancia que puede comportarse como ácido o como base según la reacción', 'Un compuesto que solo existe en estado gaseoso', 'Un metal que no reacciona con nada'], correctIndex: 0, explanation: 'El agua es un ejemplo clásico: puede aceptar o donar protones dependiendo de con qué reaccione.' },
  { id: 'quimica-adulto-05', level: 'adulto', category: 'quimica', question: '¿Qué establece el principio de Le Chatelier?', options: ['Que un sistema en equilibrio se ajusta para contrarrestar cualquier cambio externo (de concentración, presión o temperatura)', 'Que todas las reacciones son irreversibles', 'Que la temperatura no afecta al equilibrio químico'], correctIndex: 0, explanation: 'Si se perturba un sistema en equilibrio, este se desplaza en la dirección que tienda a reducir el efecto de esa perturbación.' },
  { id: 'quimica-adulto-06', level: 'adulto', category: 'quimica', question: '¿Qué distingue a un ácido fuerte de uno débil?', options: ['Un ácido fuerte se disocia completamente en agua; uno débil solo parcialmente', 'Un ácido fuerte siempre quema más rápido', 'Solo se diferencian por el color'], correctIndex: 0, explanation: 'La "fuerza" de un ácido depende de qué tan completamente se ioniza en solución acuosa, no de qué tan concentrado esté.' },
  { id: 'quimica-adulto-07', level: 'adulto', category: 'quimica', question: '¿Qué es la electronegatividad?', options: ['La tendencia de un átomo a atraer electrones hacia sí en un enlace químico', 'La cantidad de electricidad que puede almacenar un átomo', 'El número de electrones libres en un metal'], correctIndex: 0, explanation: 'Elementos como el flúor y el oxígeno tienen alta electronegatividad, lo que explica por qué ciertos enlaces (como en el agua) son polares.' },
  { id: 'quimica-adulto-08', level: 'adulto', category: 'quimica', question: '¿Qué es un polímero?', options: ['Una molécula grande formada por muchas unidades repetidas (monómeros) enlazadas', 'Un átomo con carga eléctrica', 'Un tipo de ácido fuerte'], correctIndex: 0, explanation: 'El plástico, el ADN y las proteínas son ejemplos de polímeros: cadenas largas formadas por unidades más pequeñas unidas químicamente.' },
  { id: 'quimica-adulto-09', level: 'adulto', category: 'quimica', question: '¿Qué mide la entropía en un sistema químico?', options: ['El grado de desorden o aleatoriedad de un sistema', 'La temperatura exacta de una reacción', 'El número de átomos presentes'], correctIndex: 0, explanation: 'La entropía cuantifica el desorden molecular; los sistemas tienden espontáneamente hacia estados de mayor entropía, como establece la segunda ley de la termodinámica.' },
  { id: 'quimica-adulto-10', level: 'adulto', category: 'quimica', question: '¿Qué distingue a una reacción redox?', options: ['Involucra transferencia de electrones entre especies, con oxidación y reducción simultáneas', 'Solo ocurre entre gases', 'Nunca libera ni absorbe energía'], correctIndex: 0, explanation: 'En una reacción de oxidación-reducción (redox), una especie pierde electrones (se oxida) mientras otra los gana (se reduce), como ocurre en la formación de óxido o en las baterías.' },
];

if (typeof module !== 'undefined' && module.exports) module.exports = { QUESTIONS };
if (typeof window !== 'undefined') window.QUESTIONS = QUESTIONS;
